backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "iluminationType"
    label: "Ilumination type"
    folder: "src/ilumination-type"
    create: true
    fields: 
      - {label: "Type name", name: "title", widget: "string"}
      - {label: "Type image", name: "image", widget: "image"}

  - name: "categories"
    label: "Categories"
    folder: "src/categories"
    create: true 
    fields: 
      - {label: "Category name", name: "title", widget: "string"}
      - {label: "Category image", name: "image", widget: "image"}
      - {label: "Ilumination type", name: "iluminationType", widget: "relation", collection: "iluminationType", valueField: "title", searchFields: "title"}

  - name: "subcategories"
    label: "Subcategories"
    folder: "src/categories/subcategories"
    create: true 
    fields: 
      - {label: "Subcategory name", name: "title", widget: "string"}
      - {label: "Subcategory image", name: image, widget: "image"}
      - {label: "Category", name: "category", widget: relation, collection: "categories", valueField: "title", searchFields: "title"}

  - name: "products"
    label: "Products"
    folder: "src/products"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: product-page} 
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "relation", collection: "categories", valueField: "title", searchFields: "title" }
      - {label: "Subcategory", name: "subcategory", widget: "relation", collection: "subcategories", valueField: "title", searchFields: "title"}
      - {label: "Product Image", name: "image", widget: "image"}
      - {label: "Serie", name: "name", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Material", name: "material", widget: "string", required: false}
      - {label: "Consumption", name: "consumption", widget: "string", required: false}
      - {label: "Voltage", name: "voltage", widget: "string", required: false}
      - {label: "Equipment", name: equipment, widget: "string", required: false}
      - {label: "Color Temperature", name: "colorTemperature", widget: "string", required: false }
      - {label: "CRI", name: "cri", widget: "string", required: false}
      - {label: "Beam Angle", name: "beamAngle", widget: "string", required: false}
      - {label: "IP", name: "ip", widget: "string", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Slider", name: "slider", widget: "list", fields: [{label: "Image", name: "image", widget: image}, {label: "Title", name: "title", widget: "string", required: false}, {label: "Caption", name: "caption", widget: "text", required: false}, {label: "Link", name: "link", widget: "string", required: false }]}
          
      - file: "src/pages/nosotros/index.md"
        label: "Us"
        name: "us"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: Title, name: title, widget: string}
           